name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  assets_audio_player: ^3.0.5
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dotted_line: ^3.1.0
  google_fonts: ^3.0.1
  gradient_widgets: ^0.6.0
  rflutter_alert: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
